indent = 2
always_for_in = false #
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = false #
pipe_to_function_call = false #
short_to_long_function_def = true
always_use_return = true
whitespace_in_kwargs = true #
annotate_untyped_fields_with_any = true #
conditional_to_if = true
separate_kwargs_with_semicolon = true