name: CI
on:
  pull_request:
  push:
    branches:
      - develop
      - release**
  workflow_dispatch:
  
jobs:
  test-stable:
    name: JL${{ matrix.version }} - ${{ matrix.arch }} - ${{ matrix.group }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      JULIA_PKG_SERVER: ""
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.11'
        os:
          - ubuntu-latest
        arch:
          - x64
        group:
          - 'basic_functional_group'
          - 'test_cases_group'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        continue-on-error: ${{ matrix.version == 'nightly' }}
        env:
          IIF_TEST_GROUP: ${{ matrix.group }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
          fail_ci_if_error: false
        if: ${{ matrix.version != 'nightly' }}

  upstream-dev-functional:
    name: Upstr Dev Functional
    runs-on: ubuntu-latest
    env: 
      JULIA_PKG_SERVER: ""
    strategy:
      fail-fast: false
      matrix:
        arch: 
          - x64
        version:
          - '1.11'
        group:
          - 'basic_functional_group'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: |
          git config --global user.name Tester
          git config --global user.email te@st.er
      - name: Upst Dev Functional
        env:
          IIF_TEST_GROUP: ${{ matrix.group }}
        run: |
          julia --project=@. --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(name="ApproxManifoldProducts",rev="develop"));'
          julia --project=@. --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(name="DistributedFactorGraphs",rev="develop"));' 
          julia --project=@. --check-bounds=yes -e 'using Pkg; Pkg.test("IncrementalInference"; coverage=false)'
        shell: bash

  upstream-dev-cases:
    name: Upstr Dev Test Cases
    runs-on: ubuntu-latest
    env: 
      JULIA_PKG_SERVER: ""
    strategy:
      fail-fast: false
      matrix:
        arch: 
          - x64
        version:
          - '1.11'
        group:
          - 'test_cases_group'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: |
          git config --global user.name Tester
          git config --global user.email te@st.er
      - name: Upstr Dev Cases
        env:
          IIF_TEST_GROUP: ${{ matrix.group }}
        run: |
          julia --project=@. --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(name="ApproxManifoldProducts",rev="develop"));'
          julia --project=@. --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(name="DistributedFactorGraphs",rev="develop"));' 
          julia --project=@. --check-bounds=yes -e 'using Pkg; Pkg.test("IncrementalInference"; coverage=false)'
        shell: bash

  test-debug-group:
    needs: [ upstream-dev-functional ]
    name: JL${{ matrix.version }} - ${{ matrix.group }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      JULIA_PKG_SERVER: ""
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        version:
          - '1.11'
        arch:
          - x64
        group:
          - 'tmp_debug_group'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          IIF_TEST_GROUP: ${{ matrix.group }}
